# Generated by Django 3.0.7 on 2020-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shennong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herb',
            options={'ordering': ['pinyin']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['pinyin']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='shennong.Ingredient', to='shennong.Herb'),
        ),
    ]
